---
name: "stale-repos"
author: "github"
description: "A GitHub Action to identify stale repos within an organization"
outputs:
  inactiveRepos:
    description: "Inactive Repos in the organization"
runs:
  using: "docker"
  image: 'docker://ghcr.io/github-community-projects/stale_repos@sha256:652c0ff12aead3ffee90bf233e7272d48eae7f9f8c45587d1ec12d41f0ba71d3' # v9
branding:
  icon: "check-square"
  color: "white"
