---
name: "stale-repos"
author: "github"
description: "A GitHub Action to identify stale repos within an organization"
outputs:
  inactiveRepos:
    description: "Inactive Repos in the organization"
runs:
  using: "docker"
  image: "docker://ghcr.io/github-community-projects/stale_repos:v9@sha256:b259f6c3d90e6e29c7d9a0644f4bf7b4004f51e08184cb3f834e98dc56de5745"
branding:
  icon: "check-square"
  color: "white"
